# Integration Dashboard Configuration
app:
  name: "Integration Dashboard"
  version: "2.4.1"
  environment: "development"  # Set directly in config.yaml to avoid Windows NODE_ENV issues
  port: 5000

# OpenAI Configuration
openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4o"
  max_tokens: 1000
  temperature: 0.7
  features:
    chat_analysis: true
    data_insights: true
    performance_recommendations: true

# Azure OpenAI Configuration (for future migration)
azure_openai:
  enabled: false
  endpoint: "${AZURE_OPENAI_ENDPOINT}"
  api_key: "${AZURE_OPENAI_API_KEY}"
  deployment_name: "${AZURE_OPENAI_DEPLOYMENT}"
  api_version: "2024-02-01"

# JanusGraph Configuration - TinkerPop Gremlin Driver Compatible
janusgraph:
  enabled: true
  useRemote: true  # Set to true to use actual JanusGraph database, false for in-memory storage
  connection:
    url: "ws://10.21.23.105:43563/gremlin"  # TinkerPop server with /gremlin endpoint
    # TinkerPop server hosting JanusGraph - standard Gremlin Server configuration
    # Alternative URLs if needed:
    # url: "ws://10.21.23.105:43563"  # Without /gremlin path
    # url: "wss://10.21.23.105:43563/gremlin"  # SSL if required
    timeout: 60000  # Increased timeout for initial connection
    ping_interval: 30000
    max_retries: 5  # Increased retries for connection stability
    connection_timeout: 10000  # Additional timeout setting
  database:
    name: "janusgraph"
    traversal_source: "g"  # Standard traversal source for TinkerPop server
    processor: ""  # Default processor for TinkerPop
  features:
    health_check: true
    schema_introspection: true
    performance_monitoring: true



# Database Configuration
database:
  type: "postgresql"
  url: "${DATABASE_URL}"
  pool:
    min: 2
    max: 10
  migrations:
    auto_run: true

# External Services Configuration  
external:
  listitems:
    url: ""  # Set to your actual external service URL, e.g., "https://your-api.com/listitems"
  workitems:
    url: ""  # Set to your WorkItem creation API endpoint, e.g., "https://your-api.com/workitems"
  janusgraph_schema:
    url: ""  # Set to your JanusGraph schema endpoint, e.g., "https://your-api.com/janusgraph/schema"
  # ASOT Work List URLs per source (only for sources that support ASOT: GTS, PAExchange, TeamCenter, SCR)
  asot_worklist:
    GTS: ""  # Set to your GTS ASOT Work List API endpoint
    PAExchange: ""  # Set to your PAExchange ASOT Work List API endpoint  
    TeamCenter: ""  # Set to your TeamCenter ASOT Work List API endpoint
    SCR: ""  # Set to your SCR ASOT Work List API endpoint
  ssl_insecure: true  # Disable SSL certificate verification for external APIs

# AI Chat Configuration
ai:
  chat_enabled: "${AI_CHAT_ENABLED}"

# WebSocket Configuration
websocket:
  path: "/ws"
  ping_interval: 30000
  reconnect_attempts: 5
  reconnect_delay_base: 1000

# Logging Configuration
logging:
  level: "info"
  format: "json"
  outputs:
    - "console"
  request_logging: true
  performance_logging: true

# Security Configuration
security:
  cors:
    enabled: true
    origins: ["*"]
  rate_limiting:
    enabled: false
    requests_per_minute: 100